#!/bin/bash

BOLD="\033[1m"
RED="\033[31m"
RESET="\033[0m"

CACHEFILEPATH="$HOME/.cache/runqemuCache"
CACHEFILEDIR="$HOME/.cache/"
CACHE_ROOTFS_PREFIX="ROOTFS_PATH="
CACHE_BZIMAGE_PREFIX="BZIMAGE_PATH="

record_pathName() {
	if [[ -f $CACHEFILEPATH ]]; then
		rm $CACHEFILEPATH
	fi

	if [[ ! -d $CACHEFILEDIR ]]; then
		mkdir -p $CACHEFILEDIR
	fi

	echo "${CACHE_ROOTFS_PREFIX}${ROOTFS_PATH}" >> $CACHEFILEPATH
	echo "${CACHE_BZIMAGE_PREFIX}${BZIMAGE_PATH}" >> $CACHEFILEPATH
	echo "Recording filepath to $CACHEFILEPATH"
	cat $CACHEFILEPATH
}

get_filePath() {
	if [[ -f $CACHEFILEPATH ]] && [[ -z $NOT_USE_CACHE ]]; then
		ROOTFS_PATH=$(cat $CACHEFILEPATH | grep $CACHE_ROOTFS_PREFIX | sed "s/^${CACHE_ROOTFS_PREFIX}//") 
		BZIMAGE_PATH=$(cat $CACHEFILEPATH | grep $CACHE_BZIMAGE_PREFIX | sed "s/^${CACHE_BZIMAGE_PREFIX}//") 
		echo "Found filepath from $CACHEFILEPATH"
		echo "Rootfs: $ROOTFS_PATH"
		echo "Bzimage: $BZIMAGE_PATH"
		[ -f $ROOTFS_PATH ] || unset ROOTFS_PATH
		[ -f $BZIMAGE_PATH ] || unset BZIMAGE_PATH
	fi

	[ -z $ROOTFS_PATH ] && ROOTFS_PATH=$(find ~ /disk/scratch/operating_systems/`whoami` -name 'Yesterday' -prune -o -name "debian.qcow2" -print | tail -n 1)
	[ -z $BZIMAGE_PAH ] && BZIMAGE_PATH=$(find ~ /disk/scratch/operating_systems/`whoami` -name 'Yesterday' -prune -o -wholename "*x86_64*bzImage" -print | tail -n 1)
	

	if [[ -z $ROOTFS_PATH ]] && [[ -f $ROOTFS_PATH ]]; then
		echo "debian.qcow2 not found"
		NOTFOUND_IMG=1
	fi

	if [[ -z $BZIMAGE_PATH ]] && [[ -z $BZIMAGE_PATH ]]; then
		echo "bzImage not found"
		NOTFOUND_IMG=1
	fi

	if [[ $NOTFOUND_IMG ]]; then
		echo "You should probably cd to /disk/scratch/<uun>?"
		exit 1
	fi

	record_pathName

	echo ""
	echo "#######################"
	echo ""
	echo -e "${BOLD}${RED}Found: ${RESET}" 
	echo "${BZIMAGE_PATH}"
	echo -e "${BOLD}${RED}Found: ${RESET}" 
	echo "${ROOTFS_PATH}"
	echo ""
	
	echo "CONTINUE? Press enter to Continue, N to quit"
	
	read -r input 
}

qemu_NoPort () {
	get_filePath	

	qemu-system-x86_64 -m 4G -smp 4 \
		-drive file="$ROOTFS_PATH" \
	       	-kernel "$BZIMAGE_PATH" \
	       	-append "root=/dev/sda1 console=ttyS0" -nographic
}

qemu_Port(){

	randNum=$(($RANDOM % 65535))
	if [[ -z $portNum ]]; then
		portNum=$randNum
	elif [[ $portNum -lt 2024 ]]; then
		echo "you shall use a port number greater than 2024, auto-assigning port number "
		portNum=$randNum
	elif [[ $portNum -gt 65535 ]]; then
		echo "Port number shall be smaller then 65535. Auto-assigning a port number"
		portNum=$randNum
	fi
	
	# get an available port 
	while [[ -n $(lsof -i:${portNum}) ]]; do
		echo "trying port number ${portNum} ..."
		portNum=`expr $(($portNum + 1)) % 65535`
	done
	
	get_filePath

	echo "	qemu-system-x86_64 -m 4G -smp 4 \ "
	echo "		-drive file=$ROOTFS_PATH \ "
	echo "	       	-kernel $BZIMAGE_PATH \ "
	echo "	       	-append "root=/dev/sda1 console=ttyS0" -nographic \ "
	echo "		-S -gdb tcp::${portNum} "

	echo -e "port number assigned: \033[1;31m ${portNum} \033[0m"

	qemu-system-x86_64 -m 4G -smp 4 \
		-drive file=$ROOTFS_PATH \
	       	-kernel $BZIMAGE_PATH \
	       	-append "root=/dev/sda1 console=ttyS0" -nographic \
		-S -gdb tcp::${portNum}
}

help () {
	echo "NAME"
	echo "		runqemu - a qemu shortcut"
	echo ""
	echo "SYNOPSIS"
	echo "		runqemu [-g] [port number]"
	echo ""
	echo "DESCRIPTION"
	echo "		runqemu is written for UoE operation system class"
	echo "		It detects the debiam.qcow2 disk image and bzImage"
	echo "		presented in current or child of current directory"	   
	echo "		and correctly run the qemu command to simualte the"
        echo "		kernel."
	echo "		If port number is presented, it will try to use the "
	echo "		given port number to connect to gdb."
	echo ""
	echo "-g: "
	echo "		connects with gdb. Auto assign a port"		
}

################
# Start of execution
################


if [[ $input == "N" ]]; then
	exit 0
fi

if [ $# -eq 0 ]; then
	qemu_NoPort
fi

while [ $# -gt 0 ]; do
	case $1 in
		-n)
			NOT_USE_CACHE="yes"
			shift
			;;
		-g)
			RUN_QEMU_PORT="yes"
			shift
			;;
		[0-9]*)
			RUN_QEMU_PORT="yes"
			portNum=$1
			shift
			;;
		*)
			help
			exit 1
			;;
	esac
done

if [[ -n $RUN_QEMU_PORT ]]; then
	qemu_Port
else 
	qemu_NoPort
fi
